### ISSUE TITLE
Add content in Home and Getting started

### ISSUE THREAD

**Issue by srishti-nema** [julia-vscode/docs#3]
The [Home](https://www.julia-vscode.org/docs/dev/)  and the [Getting Started](https://www.julia-vscode.org/docs/dev/gettingstarted/) pages are completely empty. I would like to create and add some text there under some guidance. I am new to this language and still in the learning phase. I came across this project through GSOD. @davidanthoff please let me know how can I begin. Thanks.

**Comment by GOVINDDIXIT** [comment]
hi, @srishti-nema Happy to know you are interested in this project. FYI I have already started auditing on these sections too as suggested in the ideas list. If you haven't yet, please take a look at the [Technical writer guide](https://developers.google.com/season-of-docs/docs/tech-writer-guide) in the Season of Docs documentation. We are currently in the Technical writer exploration phase, which is intended for those who are interested to explore projects and ideas.
You can follow the timeline [here ](https://developers.google.com/season-of-docs/docs/timeline) and start working on drafting the proposal if you are also interested to apply as a technical writer in GSoD.

**Comment by srishti-nema** [comment]
@GOVINDDIXIT  @davidanthoff I can start with something else as well. Some of the other sections are empty too. We can also enhance this repository as well. The README is also pretty old. I don't know whether I can start working now or not. Let me know when and how can I proceed.

**Comment by sbgidlow** [comment]
We have added a home page and a getting started. Closing this issue.
