### ISSUE TITLE
Rendering of docs fails in julia-vscode.org

### ISSUE THREAD

**Issue by nilsmartel** [julia-vscode/docs#46]
see this page: https://www.julia-vscode.org/docs/stable/userguide/env/

<img width="866" alt="grafik" src="https://user-images.githubusercontent.com/28377948/135748780-dc232cda-cd2e-4fdb-8a90-e912dc2b138a.png">

I am unsure how this happens, as the markdown is in the usual format (e.g. I expected the issue to be because inline html was used, but it was not)

**Comment by davidanthoff** [comment]
Hm, that link looks good on my end... Are you using some non-standard browser?

**Comment by nilsmartel** [comment]
i was using wither safari or firefox, though i can't reproduce the issue and will therefore close it
