### ISSUE TITLE
Old Changelog in docs

### ISSUE THREAD

**Issue by fkastner** [julia-vscode/docs#56]
I just noticed that the [changelog](https://www.julia-vscode.org/docs/stable/changelog/) is not updated with every release.
In particular the [dev-docs](https://www.julia-vscode.org/docs/dev/changelog/) show an older changelog than the stable/v1.5/v1.5.10 [docs](https://www.julia-vscode.org/docs/stable/changelog/).
I think I understand why this is (because it's a different repo), but maybe there is a way to fix this.

**Comment by pfitzseb** [comment]
dev is up to date now, but the underlying issue isn't really fixable I think.
