### ISSUE TITLE
Debugging in Julia is too slow

### ISSUE THREAD

**Issue by JuanVargas** [julia-vscode/docs#90]
Debugging in Julia is is too slow. I am not the only one who has inquired about this problem, which IMHO is a deal breaker.

Could someone in the Julia dev team let me (us) know what are the plans to improve the debugging experience, which currently is impossible?

Thank you

**Comment by pfitzseb** [comment]
This isn't the place for that discussion/question. Please open a topic on [discourse](https://discourse.julialang.org/) instead.

**Comment by JuanVargas** [comment]
will do . thank you
